import { StyleSheet } from 'react-native';
import {
  ThemeColors,
  FONT_DISPLAY_BOLD,
  FONT_DISPLAY_EXTRABOLD,
  FONT_BODY_REGULAR,
  FONT_BODY_MEDIUM,
  FONT_BODY_BOLD,
  FONT_BODY_SEMIBOLD,
} from '../../constants/theme';

export const createSetupStyles = (c: ThemeColors, isDark: boolean) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: c.bg },
    header: {
      backgroundColor: c.surfaceLight,
      padding: 20,
      paddingTop: 16,
      flexDirection: 'row',
      alignItems: 'center',
    },
    headerTitle: {
      fontFamily: FONT_DISPLAY_EXTRABOLD,
      fontSize: 20,
      color: c.text,
    },
    courtText: {
      fontFamily: FONT_BODY_MEDIUM,
      fontSize: 11,
      color: c.accent,
    },
    backBtn: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: c.surface,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    saveHeaderBtn: {
      backgroundColor: c.accent,
      paddingVertical: 8,
      paddingHorizontal: 20,
      borderRadius: 10,
    },
    saveHeaderText: {
      color: c.bg,
      fontFamily: FONT_BODY_BOLD,
      fontSize: 12,
    },
    chipRow: {
      flexDirection: 'row',
      gap: 6,
      paddingHorizontal: 20,
      paddingVertical: 12,
      backgroundColor: c.surfaceLight,
    },
    chip: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 6,
    },
    chipText: {
      fontFamily: FONT_BODY_SEMIBOLD,
      fontSize: 11,
    },
    modeSelector: {
      flexDirection: 'row',
      marginHorizontal: 20,
      marginTop: 8,
      marginBottom: 4,
      borderRadius: 14,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: c.border,
    },
    modeBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 12,
      backgroundColor: c.surface,
    },
    modeBtnActive: { backgroundColor: c.accent },
    modeBtnText: {
      fontFamily: FONT_DISPLAY_BOLD,
      fontSize: 11,
      color: c.textMuted,
      letterSpacing: 0.5,
    },
    modeBtnTextActive: { color: c.bg },
    toggleInfo: {
      fontFamily: FONT_BODY_REGULAR,
      fontSize: 12,
      color: c.textMuted,
      textAlign: 'center',
      paddingVertical: 4,
    },
    actionButtons: { flexDirection: 'row', padding: 16, gap: 10 },
    createMatchBtn: {
      flex: 1,
      backgroundColor: c.accent,
      borderRadius: 14,
      padding: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    createMatchBtnText: {
      color: c.bg,
      fontFamily: FONT_DISPLAY_BOLD,
      fontSize: 14,
    },
    editPlayersBtn: {
      flex: 1,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.glassStroke,
      borderRadius: 14,
      padding: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    editPlayersBtnText: {
      color: c.textSoft,
      fontFamily: FONT_DISPLAY_BOLD,
      fontSize: 14,
    },
    inputArea: { paddingHorizontal: 20, paddingBottom: 12 },
    inputRow: { flexDirection: 'row', gap: 10, alignItems: 'center' },
    input: {
      flex: 1,
      backgroundColor: c.inputBg,
      borderWidth: 1,
      borderColor: c.glassStroke,
      borderRadius: 14,
      paddingHorizontal: 16,
      fontSize: 15,
      fontFamily: FONT_BODY_REGULAR,
      color: c.inputText,
      height: 48,
    },
    genderBtn: {
      width: 48,
      height: 48,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 14,
    },
    maleActive: { backgroundColor: c.male },
    femaleActive: { backgroundColor: c.female },
    addBtn: {
      backgroundColor: c.card,
      borderWidth: 1,
      borderColor: c.glassStroke,
      width: 48,
      height: 48,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 14,
    },
    phoneToggle: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingTop: 10,
    },
    phoneToggleText: {
      color: c.secondary,
      fontSize: 13,
      fontFamily: FONT_BODY_SEMIBOLD,
    },
    phoneRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingTop: 10 },
    phoneInput: {
      flex: 1,
      backgroundColor: c.inputBg,
      borderWidth: 1,
      borderColor: c.glassStroke,
      borderRadius: 14,
      paddingHorizontal: 16,
      fontSize: 16,
      fontFamily: FONT_BODY_REGULAR,
      color: c.inputText,
      height: 40,
    },
    searchDropdown: {
      backgroundColor: c.surfaceLight,
      borderTopWidth: 1,
      borderColor: c.border,
      marginTop: 8,
      borderRadius: 12,
      paddingBottom: 5,
    },
    searchHeader: {
      fontSize: 10,
      fontFamily: FONT_BODY_BOLD,
      color: c.textMuted,
      paddingHorizontal: 15,
      paddingTop: 8,
      paddingBottom: 4,
      letterSpacing: 1,
    },
    searchRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 15,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderColor: c.border,
    },
    searchName: { fontSize: 15, fontFamily: FONT_DISPLAY_BOLD, color: c.text },
    searchMeta: {
      fontSize: 11,
      fontFamily: FONT_BODY_REGULAR,
      color: c.textMuted,
      marginTop: 2,
    },
    listContent: { padding: 20, paddingBottom: 350 },
    playerRow: {
      backgroundColor: c.card,
      padding: 14,
      borderRadius: 16,
      marginBottom: 8,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: c.border,
    },
    playerInfo: { flexDirection: 'row', alignItems: 'center', flex: 1 },
    dragHandle: { padding: 4 },
    genderIcon: {
      width: 36,
      height: 36,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: 10,
    },
    playerName: { fontFamily: FONT_DISPLAY_BOLD, fontSize: 16, color: c.text },
    playerStats: {
      fontFamily: FONT_BODY_REGULAR,
      fontSize: 11,
      color: c.textMuted,
      marginTop: 2,
    },
    emptyText: {
      textAlign: 'center',
      marginTop: 50,
      color: c.textMuted,
      fontSize: 15,
      fontFamily: FONT_BODY_REGULAR,
      paddingHorizontal: 30,
    },
    // Info modal
    infoText: {
      fontSize: 15,
      fontFamily: FONT_BODY_REGULAR,
      color: c.textSoft,
      lineHeight: 22,
    },
    infoCloseBtn: {
      backgroundColor: c.accent,
      borderRadius: 14,
      padding: 15,
      marginTop: 20,
      alignItems: 'center',
    },
    infoCloseBtnText: {
      color: c.bg,
      fontFamily: FONT_DISPLAY_EXTRABOLD,
      fontSize: 16,
    },
    // Modals
    modalOverlay: {
      flex: 1,
      backgroundColor: c.modalOverlay,
      justifyContent: 'center',
      padding: 20,
    },
    modalContent: {
      backgroundColor: c.modalBg,
      borderRadius: 20,
      padding: 25,
      maxHeight: '90%',
    },
    modalTitle: {
      fontFamily: FONT_DISPLAY_EXTRABOLD,
      fontSize: 22,
      color: c.text,
      textAlign: 'center',
      marginBottom: 20,
    },
    modalInput: {
      borderWidth: 1,
      borderColor: c.inputBorder,
      backgroundColor: c.inputBg,
      borderRadius: 14,
      padding: 12,
      fontSize: 16,
      fontFamily: FONT_BODY_MEDIUM,
      color: c.inputText,
      marginBottom: 10,
    },
    saveOptionBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 15,
      padding: 15,
      borderRadius: 14,
      backgroundColor: c.accent,
      marginBottom: 10,
    },
    saveOptionText: {
      fontFamily: FONT_DISPLAY_EXTRABOLD,
      fontSize: 16,
      color: c.bg,
    },
    closeModalBtn: { marginTop: 10, alignItems: 'center', padding: 10 },
    closeText: { color: c.textMuted, fontFamily: FONT_BODY_BOLD },
    fieldLabel: {
      fontFamily: FONT_BODY_SEMIBOLD,
      fontSize: 12,
      color: c.textMuted,
      letterSpacing: 1,
      textTransform: 'uppercase',
    },
    modalBtn: { alignItems: 'center', justifyContent: 'center', padding: 14, borderRadius: 14 },
    modalBtnText: {
      fontFamily: FONT_DISPLAY_EXTRABOLD,
      fontSize: 15,
      letterSpacing: 0.5,
    },
    editGenderBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flex: 1,
      justifyContent: 'center',
      padding: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
    },
    courtDisplayBar: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: c.accentSoft,
      padding: 10,
      borderRadius: 10,
      marginBottom: 15,
    },
    courtDisplayText: {
      flex: 1,
      fontFamily: FONT_BODY_BOLD,
      color: c.accent,
      fontSize: 14,
    },
    infoBox: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 10,
      marginBottom: 20,
      backgroundColor: c.surfaceLight,
      padding: 10,
      borderRadius: 10,
    },
    infoBoxText: { fontFamily: FONT_BODY_BOLD, color: c.textSoft },
    counterRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
    },
    label: { fontSize: 14, fontFamily: FONT_BODY_BOLD, color: c.textMuted },
    roundControls: { flexDirection: 'row', alignItems: 'center', gap: 15 },
    roundBtn: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: c.surfaceLight,
      justifyContent: 'center',
      alignItems: 'center',
    },
    roundCountText: {
      fontSize: 20,
      fontFamily: FONT_DISPLAY_EXTRABOLD,
      color: c.text,
    },
    roundConfigRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
      paddingVertical: 5,
      borderBottomWidth: 1,
      borderColor: c.border,
    },
    roundNum: { width: 30, fontFamily: FONT_BODY_BOLD, color: c.textMuted },
    toggleGroup: { flex: 1, flexDirection: 'row', gap: 5 },
    smallTypeBtn: {
      flex: 1,
      paddingVertical: 8,
      borderRadius: 8,
      backgroundColor: c.surfaceLight,
      alignItems: 'center',
    },
    smallTypeActive: { backgroundColor: c.accent },
    smallTypeText: { fontSize: 10, fontFamily: FONT_BODY_BOLD, color: c.textMuted },
    startMatchBtn: {
      backgroundColor: c.accent,
      padding: 15,
      borderRadius: 14,
      marginTop: 10,
      alignItems: 'center',
    },
    startMatchText: {
      color: c.bg,
      fontFamily: FONT_DISPLAY_EXTRABOLD,
      fontSize: 16,
    },
  });
